export const DEFAULT_LANGUAGE = "en";

const en = {
  meta: {
    label: "English",
    nativeName: "English",
    dir: "ltr",
    locale: "en-US",
  },

  header: {
    /* `nav` items are now objects so they can actually route. Add a `path` and
       it becomes a real link; the label is what gets translated. */
    nav: [
      { key: "discover", label: "Discover", path: "/browse" },
      { key: "watchlist", label: "Watchlist", path: "/my-list" },
    ],
    gptSearch: "Goto GPT Search",
    exitGptSearch: "Back to browse",
    language: "Language",
    signOut: "Sign out",
    account: "Account",
  },

  hero: {
    featured: "Featured today",
    noTrailer: "No trailer available",
    mute: "Mute trailer",
    unmute: "Unmute trailer",
    replay: "Replay trailer",
  },

  gpt: {
    badge: "AI-powered search",
    heading: "What are you in the mood for?",
    subheading: "Describe a mood, a mashup, or a scene you half-remember.",
    placeholder: "e.g. an Indian horror-comedy that isn't actually scary",
    search: "Search",
    searching: "Searching…",
    clear: "Clear",
    tryLabel: "Try one of these",
    resultsFor: 'Results for "{query}"',
    resultsCount: "{n} titles matched",
    aiPick: "AI pick",
    suggestedBy: "Suggested by Gemini",
    noMatchHeading: "Suggested but not found on TMDB",
    noMatchHelp:
      "Gemini named these, but TMDB had no match — usually a spelling or regional-title mismatch.",
    emptyHeading: "Ask CineGPT for anything",
    emptyBody:
      "Genre filters can't find “the one with the rotating hallway.” Describe it in your own words instead.",
    suggestions: [
      "Indian horror-comedy",
      "The one with the rotating hallway",
      "Slow-burn Korean thrillers",
      "Heist films with no violence",
      "Sci-fi that made me cry",
    ],
  },

  search: {
    label: "Search titles",
    placeholder: "Search by title, e.g. Inception",
    submit: "Search",
    clear: "Clear search",
    resultsFor: 'Results for "{query}"',
    resultsCount: "{n} titles found",
    noResultsHeading: "No titles matched",
    noResultsBody:
      "Try fewer words, or check the spelling. Titles are matched exactly — for descriptions and moods, use GPT Search.",
    topMatches: "Best matches",
    topMatchesSub: "Closest to what you typed",
    decade: "{decade}s",
    decadeSub: "Released {decade}–{decadeEnd}",
    undated: "No release date",
    undatedSub: "Unreleased or missing metadata on TMDB",
  },

  rows: {
    nowPlaying: "Now playing",
    nowPlayingSub: "In theatres this week",
    topRated: "Top rated right now",
    topRatedSub: "Ranked by TMDB user score",
    trending: "Trending with viewers",
    trendingSub: "Highest momentum today",
    seeAll: "See all",
    collapse: "Show less",
    scrollLeft: "Scroll left",
    scrollRight: "Scroll right",
  },

  card: {
    noOverview: "No description available.",
    /* "Watchlist" over "My List" — it says what the list is FOR (save now,
       watch later) instead of just who owns it. Same word on the card button,
       the nav item and the page heading, so they read as one feature. */
    save: "Watchlist",
    saved: "Saved",
    saving: "Saving",
    saveAria: "Add {title} to your watchlist",
    savedAria: "{title} is in your watchlist",
  },

  myList: {
    title: "Your Watchlist",
    subtitle: "Everything you've saved, in one place.",
    count: "{n} saved",
    countOne: "1 saved",
    emptyHeading: "Nothing saved yet",
    emptyBody:
      "Hit Watchlist on any poster and it'll show up here — a place to park the films you'll actually get around to.",
    emptyCta: "Browse titles",
    sortLabel: "Sort",
    sortRecent: "Recently added",
    sortTitle: "Title A–Z",
    sortRating: "Highest rated",
    sortYear: "Newest first",
    statTitles: "Titles",
    statAvgRating: "Avg. rating",
    statDecades: "Decades",
  },

  detail: {
    back: "Back",
    overview: "Overview",
    noOverview: "No description available.",
    details: "Details",
    status: "Status",
    releaseDate: "Release date",
    runtime: "Runtime",
    minutes: "min",
    originalLanguage: "Original language",
    originalTitle: "Original title",
    budget: "Budget",
    revenue: "Revenue",
    genres: "Genres",
    productionCompanies: "Production",
    countries: "Countries",
    voteCount: "{n} votes",
    cast: "Top billed cast",
    crew: "Key crew",
    watchOn: "Where to watch",
    noProviders: "No streaming providers listed for your region.",
    trailer: "Trailer",
    noTrailer: "No trailer available.",
    similar: "More like this",
    notAvailable: "—",
    fromBrowse: "Browse",
    fromSearch: "Search results",
    fromGpt: "GPT Search",
  },

  footer: { note: "A learning project.", dataBy: "Movie data by TMDB." },

  auth: {
    signIn: "Sign in",
    signUp: "Create account",
    welcomeBack: "Welcome back",
    createAccount: "Create your account",
    signInSubtitle: "Sign in to pick up where you left off.",
    signUpSubtitle: "Free to start. No card required.",
    fullName: "Full name",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm password",
    forgotPassword: "Forgot password?",
    or: "or",
    continueWithGoogle: "Continue with Google",
    haveAccount: "Already have an account?",
    noAccount: "New to CineGPT?",
    createOne: "Create one",
    showPassword: "Show password",
    hidePassword: "Hide password",
  },
};

const hi = {
  meta: { label: "Hindi", nativeName: "हिन्दी", dir: "ltr", locale: "hi-IN" },

  header: {
    nav: [
      { key: "discover", label: "खोजें", path: "/browse" },
      { key: "watchlist", label: "वॉचलिस्ट", path: "/my-list" },
    ],
    gptSearch: "GPT खोज",
    exitGptSearch: "ब्राउज़ पर वापस",
    language: "भाषा",
    signOut: "साइन आउट",
    account: "खाता",
  },

  hero: {
    featured: "आज का चयन",
    noTrailer: "ट्रेलर उपलब्ध नहीं",
    mute: "ट्रेलर म्यूट करें",
    unmute: "ट्रेलर अनम्यूट करें",
    replay: "ट्रेलर दोबारा चलाएँ",
  },

  gpt: {
    badge: "AI-आधारित खोज",
    heading: "आपका आज क्या देखने का मन है?",
    subheading:
      "कोई मूड, कोई मिक्स, या कोई अधूरा याद रहा सीन — जैसा याद है वैसा लिखें।",
    placeholder: "जैसे: एक भारतीय हॉरर-कॉमेडी जो असल में डरावनी न हो",
    search: "खोजें",
    searching: "खोज रहे हैं…",
    clear: "साफ़ करें",
    tryLabel: "इनमें से कोई आज़माएँ",
    resultsFor: '"{query}" के परिणाम',
    resultsCount: "{n} फ़िल्में मिलीं",
    aiPick: "AI सुझाव",
    suggestedBy: "Gemini द्वारा सुझाया गया",
    noMatchHeading: "सुझाई गईं, लेकिन TMDB पर नहीं मिलीं",
    noMatchHelp:
      "Gemini ने इनके नाम दिए, पर TMDB पर मिलान नहीं हुआ — आमतौर पर स्पेलिंग या क्षेत्रीय नाम के अंतर के कारण।",
    emptyHeading: "CineGPT से कुछ भी पूछें",
    emptyBody:
      "जॉनर फ़िल्टर “वह वाली जिसमें गलियारा घूमता है” नहीं खोज सकते। अपने शब्दों में बताइए।",
    suggestions: [
      "भारतीय हॉरर-कॉमेडी",
      "वह वाली जिसमें घूमने वाला गलियारा है",
      "धीमी रफ़्तार वाली कोरियाई थ्रिलर",
      "बिना हिंसा वाली डकैती फ़िल्में",
      "साइ-फ़ाई जिसने मुझे रुला दिया",
    ],
  },

  search: {
    label: "फ़िल्में खोजें",
    placeholder: "नाम से खोजें, जैसे Inception",
    submit: "खोजें",
    clear: "खोज हटाएँ",
    resultsFor: '"{query}" के परिणाम',
    resultsCount: "{n} फ़िल्में मिलीं",
    noResultsHeading: "कोई फ़िल्म नहीं मिली",
    noResultsBody:
      "कम शब्द आज़माएँ, या स्पेलिंग जाँचें। यहाँ नाम से ही मिलान होता है — विवरण या मूड से खोजने के लिए GPT खोज इस्तेमाल करें।",
    topMatches: "सबसे सटीक मिलान",
    topMatchesSub: "आपने जो लिखा उसके सबसे क़रीब",
    decade: "{decade} का दशक",
    decadeSub: "{decade}–{decadeEnd} में रिलीज़",
    undated: "रिलीज़ तारीख़ नहीं",
    undatedSub: "अनरिलीज़्ड या TMDB पर जानकारी अनुपलब्ध",
  },

  rows: {
    nowPlaying: "अभी सिनेमाघरों में",
    nowPlayingSub: "इस हफ़्ते सिनेमाघरों में",
    topRated: "सबसे ज़्यादा रेटिंग वाली",
    topRatedSub: "TMDB यूज़र स्कोर के अनुसार",
    trending: "दर्शकों में लोकप्रिय",
    trendingSub: "आज सबसे ज़्यादा चर्चा में",
    seeAll: "सभी देखें",
    collapse: "कम दिखाएँ",
    scrollLeft: "बाएँ स्क्रॉल करें",
    scrollRight: "दाएँ स्क्रॉल करें",
  },

  card: {
    noOverview: "कोई विवरण उपलब्ध नहीं।",
    save: "वॉचलिस्ट",
    saved: "सेव किया",
    saving: "सेव हो रहा है",
    saveAria: "{title} को वॉचलिस्ट में जोड़ें",
    savedAria: "{title} आपकी वॉचलिस्ट में है",
  },

  myList: {
    title: "आपकी वॉचलिस्ट",
    subtitle: "आपने जो कुछ सेव किया, सब एक जगह।",
    count: "{n} सेव किए",
    countOne: "1 सेव किया",
    emptyHeading: "अभी कुछ सेव नहीं किया",
    emptyBody:
      "किसी भी पोस्टर पर वॉचलिस्ट दबाएँ और वह यहाँ दिखने लगेगी — जो फ़िल्में आप असल में देखेंगे, उन्हें यहाँ रखें।",
    emptyCta: "फ़िल्में देखें",
    sortLabel: "क्रम",
    sortRecent: "हाल में जोड़ी गईं",
    sortTitle: "नाम अ–ज्ञ",
    sortRating: "सबसे अधिक रेटिंग",
    sortYear: "सबसे नई पहले",
    statTitles: "फ़िल्में",
    statAvgRating: "औसत रेटिंग",
    statDecades: "दशक",
  },

  detail: {
    back: "वापस",
    overview: "कहानी",
    noOverview: "कोई विवरण उपलब्ध नहीं।",
    details: "विवरण",
    status: "स्थिति",
    releaseDate: "रिलीज़ तारीख़",
    runtime: "अवधि",
    minutes: "मिनट",
    originalLanguage: "मूल भाषा",
    originalTitle: "मूल नाम",
    budget: "बजट",
    revenue: "कमाई",
    genres: "शैली",
    productionCompanies: "निर्माण",
    countries: "देश",
    voteCount: "{n} वोट",
    cast: "मुख्य कलाकार",
    crew: "मुख्य टीम",
    watchOn: "कहाँ देखें",
    noProviders: "आपके क्षेत्र के लिए कोई स्ट्रीमिंग प्रोवाइडर नहीं मिला।",
    trailer: "ट्रेलर",
    noTrailer: "ट्रेलर उपलब्ध नहीं।",
    similar: "इससे मिलती-जुलती",
    notAvailable: "—",
    fromBrowse: "ब्राउज़",
    fromSearch: "खोज परिणाम",
    fromGpt: "GPT खोज",
  },

  footer: {
    note: "एक लर्निंग प्रोजेक्ट।",
    dataBy: "फ़िल्म डेटा TMDB से।",
  },

  auth: {
    signIn: "साइन इन",
    signUp: "खाता बनाएँ",
    welcomeBack: "फिर से स्वागत है",
    createAccount: "अपना खाता बनाएँ",
    signInSubtitle: "जहाँ छोड़ा था वहीं से शुरू करें।",
    signUpSubtitle: "शुरू करना मुफ़्त है। कार्ड की ज़रूरत नहीं।",
    fullName: "पूरा नाम",
    email: "ईमेल",
    password: "पासवर्ड",
    confirmPassword: "पासवर्ड की पुष्टि करें",
    forgotPassword: "पासवर्ड भूल गए?",
    or: "या",
    continueWithGoogle: "Google से जारी रखें",
    haveAccount: "पहले से खाता है?",
    noAccount: "CineGPT पर नए हैं?",
    createOne: "खाता बनाएँ",
    showPassword: "पासवर्ड दिखाएँ",
    hidePassword: "पासवर्ड छिपाएँ",
  },
};

const ta = {
  meta: { label: "Tamil", nativeName: "தமிழ்", dir: "ltr", locale: "ta-IN" },

  header: {
    nav: [
      { key: "discover", label: "கண்டறி", path: "/browse" },
      { key: "watchlist", label: "பார்க்க வேண்டியவை", path: "/my-list" },
    ],
    gptSearch: "GPT தேடல்",
    exitGptSearch: "உலாவலுக்குத் திரும்பு",
    language: "மொழி",
    signOut: "வெளியேறு",
    account: "கணக்கு",
  },

  hero: {
    featured: "இன்றைய சிறப்புத் தேர்வு",
    noTrailer: "டிரெய்லர் கிடைக்கவில்லை",
    mute: "டிரெய்லரை ஒலியடக்கு",
    unmute: "டிரெய்லர் ஒலியை இயக்கு",
    replay: "டிரெய்லரை மீண்டும் இயக்கு",
  },

  gpt: {
    badge: "AI அடிப்படையிலான தேடல்",
    heading: "இன்று எதைப் பார்க்க விருப்பம்?",
    subheading:
      "ஒரு மனநிலை, ஒரு கலவை, அல்லது பாதி நினைவில் உள்ள ஒரு காட்சி — உங்கள் வார்த்தைகளில் சொல்லுங்கள்.",
    placeholder: "எ.கா. பயமே இல்லாத ஒரு இந்திய திகில்-நகைச்சுவைப் படம்",
    search: "தேடு",
    searching: "தேடுகிறது…",
    clear: "அழி",
    tryLabel: "இவற்றில் ஒன்றை முயற்சிக்கவும்",
    resultsFor: '"{query}" க்கான முடிவுகள்',
    resultsCount: "{n} படங்கள் பொருந்தின",
    aiPick: "AI தேர்வு",
    suggestedBy: "Gemini பரிந்துரைத்தது",
    noMatchHeading: "பரிந்துரைக்கப்பட்டன, ஆனால் TMDB இல் இல்லை",
    noMatchHelp:
      "Gemini இவற்றைப் பரிந்துரைத்தது, ஆனால் TMDB இல் பொருத்தம் கிடைக்கவில்லை — பொதுவாக எழுத்துப்பிழை அல்லது வேறு பெயர் காரணமாக.",
    emptyHeading: "CineGPT இடம் எதையும் கேளுங்கள்",
    emptyBody:
      "“அந்த சுழலும் நடைபாதை வரும் படம்” என்பதை வகைப் வடிகட்டிகள் கண்டுபிடிக்க முடியாது. உங்கள் சொற்களில் விவரியுங்கள்.",
    suggestions: [
      "இந்திய திகில்-நகைச்சுவைப் படம்",
      "சுழலும் நடைபாதை வரும் அந்தப் படம்",
      "மெதுவாக விரியும் கொரிய த்ரில்லர்கள்",
      "வன்முறை இல்லாத கொள்ளையர் படங்கள்",
      "என்னை அழ வைத்த அறிவியல் புனைவு",
    ],
  },

  search: {
    label: "படங்களைத் தேடு",
    placeholder: "பெயரால் தேடுங்கள், எ.கா. Inception",
    submit: "தேடு",
    clear: "தேடலை அழி",
    resultsFor: '"{query}" க்கான முடிவுகள்',
    resultsCount: "{n} படங்கள் கிடைத்தன",
    noResultsHeading: "எந்தப் படமும் கிடைக்கவில்லை",
    noResultsBody:
      "குறைவான சொற்களை முயற்சிக்கவும், அல்லது எழுத்துப்பிழையைச் சரிபார்க்கவும். இங்கே பெயரால் மட்டுமே பொருத்தம் — விவரம் அல்லது மனநிலையால் தேட GPT தேடலைப் பயன்படுத்தவும்.",
    topMatches: "சிறந்த பொருத்தங்கள்",
    topMatchesSub: "நீங்கள் தட்டச்சு செய்ததற்கு மிக நெருக்கமானவை",
    decade: "{decade} கள்",
    decadeSub: "{decade}–{decadeEnd} இல் வெளியானவை",
    undated: "வெளியீட்டு தேதி இல்லை",
    undatedSub: "வெளியாகாதவை அல்லது TMDB இல் தகவல் இல்லை",
  },

  rows: {
    nowPlaying: "இப்போது திரையில்",
    nowPlayingSub: "இந்த வாரம் திரையரங்குகளில்",
    topRated: "தற்போது அதிக மதிப்பெண்",
    topRatedSub: "TMDB பயனர் மதிப்பெண் அடிப்படையில்",
    trending: "பார்வையாளர்களிடையே பிரபலம்",
    trendingSub: "இன்று அதிக கவனம் பெற்றவை",
    seeAll: "அனைத்தையும் காண",
    collapse: "குறைவாகக் காட்டு",
    scrollLeft: "இடதுபுறம் நகர்த்து",
    scrollRight: "வலதுபுறம் நகர்த்து",
  },

  card: {
    noOverview: "விவரம் இல்லை.",
    save: "பட்டியலில் சேர்",
    saved: "சேர்க்கப்பட்டது",
    saving: "சேமிக்கிறது",
    saveAria: "{title} ஐ உங்கள் பட்டியலில் சேர்",
    savedAria: "{title} உங்கள் பட்டியலில் உள்ளது",
  },

  myList: {
    title: "பார்க்க வேண்டியவை",
    subtitle: "நீங்கள் சேமித்த அனைத்தும் ஒரே இடத்தில்.",
    count: "{n} சேமிக்கப்பட்டவை",
    countOne: "1 சேமிக்கப்பட்டது",
    emptyHeading: "இன்னும் எதுவும் சேமிக்கப்படவில்லை",
    emptyBody:
      "எந்தப் போஸ்டரிலும் சேர் என்பதை அழுத்தினால் அது இங்கே தோன்றும் — நீங்கள் நிச்சயம் பார்க்கப் போகும் படங்களை இங்கே வைத்துக்கொள்ளுங்கள்.",
    emptyCta: "படங்களைக் காண",
    sortLabel: "வரிசை",
    sortRecent: "சமீபத்தில் சேர்த்தவை",
    sortTitle: "பெயர் அ–ஃ",
    sortRating: "அதிக மதிப்பெண்",
    sortYear: "புதியவை முதலில்",
    statTitles: "படங்கள்",
    statAvgRating: "சராசரி மதிப்பெண்",
    statDecades: "தசாப்தங்கள்",
  },

  detail: {
    back: "பின் செல்",
    overview: "கதைச்சுருக்கம்",
    noOverview: "விவரம் இல்லை.",
    details: "விவரங்கள்",
    status: "நிலை",
    releaseDate: "வெளியீட்டு தேதி",
    runtime: "ஓட்ட நேரம்",
    minutes: "நிமிடம்",
    originalLanguage: "மூல மொழி",
    originalTitle: "மூலப் பெயர்",
    budget: "தயாரிப்புச் செலவு",
    revenue: "வசூல்",
    genres: "வகைகள்",
    productionCompanies: "தயாரிப்பு",
    countries: "நாடுகள்",
    voteCount: "{n} வாக்குகள்",
    cast: "முக்கிய நடிகர்கள்",
    crew: "முக்கியக் குழு",
    watchOn: "எங்கே பார்க்கலாம்",
    noProviders: "உங்கள் பகுதிக்கு ஸ்ட்ரீமிங் சேவைகள் பட்டியலிடப்படவில்லை.",
    trailer: "டிரெய்லர்",
    noTrailer: "டிரெய்லர் கிடைக்கவில்லை.",
    similar: "இதைப் போன்றவை",
    notAvailable: "—",
    fromBrowse: "உலாவல்",
    fromSearch: "தேடல் முடிவுகள்",
    fromGpt: "GPT தேடல்",
  },

  footer: {
    note: "ஒரு கற்றல் திட்டம்.",
    dataBy: "திரைப்பட தகவல் TMDB வழங்கியது.",
  },

  auth: {
    signIn: "உள்நுழை",
    signUp: "கணக்கை உருவாக்கு",
    welcomeBack: "மீண்டும் வருக",
    createAccount: "உங்கள் கணக்கை உருவாக்குங்கள்",
    signInSubtitle: "நிறுத்திய இடத்திலிருந்து தொடருங்கள்.",
    signUpSubtitle: "தொடங்க இலவசம். கார்டு தேவையில்லை.",
    fullName: "முழுப் பெயர்",
    email: "மின்னஞ்சல்",
    password: "கடவுச்சொல்",
    confirmPassword: "கடவுச்சொல்லை உறுதிப்படுத்து",
    forgotPassword: "கடவுச்சொல் மறந்துவிட்டதா?",
    or: "அல்லது",
    continueWithGoogle: "Google மூலம் தொடரவும்",
    haveAccount: "ஏற்கனவே கணக்கு உள்ளதா?",
    noAccount: "CineGPT இல் புதியவரா?",
    createOne: "கணக்கை உருவாக்கு",
    showPassword: "கடவுச்சொல்லைக் காட்டு",
    hidePassword: "கடவுச்சொல்லை மறை",
  },
};

export const languageConstants = { en, hi, ta };

export const getLanguage = (identifier) =>
  languageConstants[identifier] ?? languageConstants[DEFAULT_LANGUAGE];

export const fill = (template, values = {}) =>
  Object.entries(values).reduce(
    (out, [key, value]) => out.replaceAll(`{${key}}`, String(value)),
    template ?? "",
  );
